import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

const WORD_DATA: Record<string, { text: string; native: string }[]> = {
  en: [
    {text:"Hello",native:"Hello"},{text:"Goodbye",native:"Goodbye"},{text:"Please",native:"Please"},{text:"Thank you",native:"Thank you"},{text:"You're welcome",native:"You're welcome"},{text:"Excuse me",native:"Excuse me"},{text:"Sorry",native:"Sorry"},{text:"Yes",native:"Yes"},{text:"No",native:"No"},{text:"Maybe",native:"Maybe"},{text:"Good morning",native:"Good morning"},{text:"Good afternoon",native:"Good afternoon"},{text:"Good evening",native:"Good evening"},{text:"Good night",native:"Good night"},{text:"How are you?",native:"How are you?"},{text:"I'm fine",native:"I'm fine"},{text:"Nice to meet you",native:"Nice to meet you"},{text:"See you later",native:"See you later"},{text:"Take care",native:"Take care"},{text:"Welcome",native:"Welcome"},
    {text:"One",native:"One"},{text:"Two",native:"Two"},{text:"Three",native:"Three"},{text:"Four",native:"Four"},{text:"Five",native:"Five"},{text:"Six",native:"Six"},{text:"Seven",native:"Seven"},{text:"Eight",native:"Eight"},{text:"Nine",native:"Nine"},{text:"Ten",native:"Ten"},{text:"Twenty",native:"Twenty"},{text:"Thirty",native:"Thirty"},{text:"Fifty",native:"Fifty"},{text:"One hundred",native:"One hundred"},{text:"One thousand",native:"One thousand"},{text:"First",native:"First"},{text:"Second",native:"Second"},{text:"Third",native:"Third"},{text:"Half",native:"Half"},{text:"Double",native:"Double"},{text:"Many",native:"Many"},{text:"Few",native:"Few"},{text:"Enough",native:"Enough"},
    {text:"Monday",native:"Monday"},{text:"Tuesday",native:"Tuesday"},{text:"Wednesday",native:"Wednesday"},{text:"Thursday",native:"Thursday"},{text:"Friday",native:"Friday"},{text:"Saturday",native:"Saturday"},{text:"Sunday",native:"Sunday"},{text:"Today",native:"Today"},{text:"Tomorrow",native:"Tomorrow"},{text:"Yesterday",native:"Yesterday"},{text:"Morning",native:"Morning"},{text:"Afternoon",native:"Afternoon"},{text:"Evening",native:"Evening"},{text:"Night",native:"Night"},{text:"Hour",native:"Hour"},{text:"Minute",native:"Minute"},{text:"Second",native:"Second"},{text:"Week",native:"Week"},{text:"Month",native:"Month"},{text:"Year",native:"Year"},{text:"Now",native:"Now"},{text:"Later",native:"Later"},{text:"Always",native:"Always"},{text:"Never",native:"Never"},{text:"Sometimes",native:"Sometimes"},
    {text:"Water",native:"Water"},{text:"Food",native:"Food"},{text:"Bread",native:"Bread"},{text:"Rice",native:"Rice"},{text:"Meat",native:"Meat"},{text:"Fish",native:"Fish"},{text:"Chicken",native:"Chicken"},{text:"Egg",native:"Egg"},{text:"Milk",native:"Milk"},{text:"Coffee",native:"Coffee"},{text:"Tea",native:"Tea"},{text:"Juice",native:"Juice"},{text:"Beer",native:"Beer"},{text:"Wine",native:"Wine"},{text:"Sugar",native:"Sugar"},{text:"Salt",native:"Salt"},{text:"Cheese",native:"Cheese"},{text:"Fruit",native:"Fruit"},{text:"Vegetable",native:"Vegetable"},{text:"Soup",native:"Soup"},{text:"Salad",native:"Salad"},{text:"Dessert",native:"Dessert"},{text:"Breakfast",native:"Breakfast"},{text:"Lunch",native:"Lunch"},{text:"Dinner",native:"Dinner"},{text:"Apple",native:"Apple"},{text:"Banana",native:"Banana"},{text:"Orange",native:"Orange"},{text:"Potato",native:"Potato"},{text:"Butter",native:"Butter"},
    {text:"Family",native:"Family"},{text:"Mother",native:"Mother"},{text:"Father",native:"Father"},{text:"Son",native:"Son"},{text:"Daughter",native:"Daughter"},{text:"Brother",native:"Brother"},{text:"Sister",native:"Sister"},{text:"Grandmother",native:"Grandmother"},{text:"Grandfather",native:"Grandfather"},{text:"Husband",native:"Husband"},{text:"Wife",native:"Wife"},{text:"Child",native:"Child"},{text:"Baby",native:"Baby"},{text:"Friend",native:"Friend"},{text:"Neighbor",native:"Neighbor"},{text:"Teacher",native:"Teacher"},{text:"Student",native:"Student"},{text:"Doctor",native:"Doctor"},{text:"Man",native:"Man"},{text:"Woman",native:"Woman"},{text:"Boy",native:"Boy"},{text:"Girl",native:"Girl"},{text:"People",native:"People"},{text:"Person",native:"Person"},{text:"Name",native:"Name"},
    {text:"House",native:"House"},{text:"Door",native:"Door"},{text:"Window",native:"Window"},{text:"Room",native:"Room"},{text:"Kitchen",native:"Kitchen"},{text:"Bathroom",native:"Bathroom"},{text:"Bedroom",native:"Bedroom"},{text:"Living room",native:"Living room"},{text:"Table",native:"Table"},{text:"Chair",native:"Chair"},{text:"Bed",native:"Bed"},{text:"Garden",native:"Garden"},{text:"Floor",native:"Floor"},{text:"Wall",native:"Wall"},{text:"Roof",native:"Roof"},{text:"Key",native:"Key"},{text:"Light",native:"Light"},{text:"Mirror",native:"Mirror"},{text:"Television",native:"Television"},{text:"Computer",native:"Computer"},{text:"Phone",native:"Phone"},{text:"Clock",native:"Clock"},{text:"Book",native:"Book"},{text:"Money",native:"Money"},{text:"Bag",native:"Bag"},
    {text:"Red",native:"Red"},{text:"Blue",native:"Blue"},{text:"Green",native:"Green"},{text:"Yellow",native:"Yellow"},{text:"Black",native:"Black"},{text:"White",native:"White"},{text:"Purple",native:"Purple"},{text:"Pink",native:"Pink"},{text:"Brown",native:"Brown"},{text:"Gray",native:"Gray"},{text:"Big",native:"Big"},{text:"Small",native:"Small"},{text:"Tall",native:"Tall"},{text:"Short",native:"Short"},{text:"Long",native:"Long"},{text:"Heavy",native:"Heavy"},{text:"Light",native:"Light"},{text:"Beautiful",native:"Beautiful"},{text:"Fast",native:"Fast"},{text:"Slow",native:"Slow"},{text:"Strong",native:"Strong"},{text:"Weak",native:"Weak"},{text:"Clean",native:"Clean"},{text:"Dirty",native:"Dirty"},{text:"New",native:"New"},{text:"Old",native:"Old"},
    {text:"Head",native:"Head"},{text:"Face",native:"Face"},{text:"Eye",native:"Eye"},{text:"Ear",native:"Ear"},{text:"Nose",native:"Nose"},{text:"Mouth",native:"Mouth"},{text:"Hand",native:"Hand"},{text:"Foot",native:"Foot"},{text:"Arm",native:"Arm"},{text:"Leg",native:"Leg"},{text:"Heart",native:"Heart"},{text:"Body",native:"Body"},{text:"Hospital",native:"Hospital"},{text:"Medicine",native:"Medicine"},{text:"Sick",native:"Sick"},{text:"Healthy",native:"Healthy"},{text:"Pain",native:"Pain"},{text:"Pharmacy",native:"Pharmacy"},{text:"Emergency",native:"Emergency"},{text:"Blood",native:"Blood"},{text:"Finger",native:"Finger"},{text:"Hair",native:"Hair"},{text:"Skin",native:"Skin"},{text:"Back",native:"Back"},{text:"Stomach",native:"Stomach"},
    {text:"Travel",native:"Travel"},{text:"Airport",native:"Airport"},{text:"Train",native:"Train"},{text:"Bus",native:"Bus"},{text:"Taxi",native:"Taxi"},{text:"Car",native:"Car"},{text:"Bicycle",native:"Bicycle"},{text:"Street",native:"Street"},{text:"Road",native:"Road"},{text:"Bridge",native:"Bridge"},{text:"Map",native:"Map"},{text:"Ticket",native:"Ticket"},{text:"Hotel",native:"Hotel"},{text:"Restaurant",native:"Restaurant"},{text:"Museum",native:"Museum"},{text:"Park",native:"Park"},{text:"Beach",native:"Beach"},{text:"Mountain",native:"Mountain"},{text:"Ocean",native:"Ocean"},{text:"Passport",native:"Passport"},{text:"Suitcase",native:"Suitcase"},{text:"Flight",native:"Flight"},{text:"Station",native:"Station"},{text:"Subway",native:"Subway"},
    {text:"To be",native:"To be"},{text:"To have",native:"To have"},{text:"To do",native:"To do"},{text:"To go",native:"To go"},{text:"To come",native:"To come"},{text:"To see",native:"To see"},{text:"To hear",native:"To hear"},{text:"To speak",native:"To speak"},{text:"To eat",native:"To eat"},{text:"To drink",native:"To drink"},{text:"To sleep",native:"To sleep"},{text:"To read",native:"To read"},{text:"To write",native:"To write"},{text:"To learn",native:"To learn"},{text:"To teach",native:"To teach"},{text:"To work",native:"To work"},{text:"To play",native:"To play"},{text:"To run",native:"To run"},{text:"To walk",native:"To walk"},{text:"To buy",native:"To buy"},{text:"To sell",native:"To sell"},{text:"To open",native:"To open"},{text:"To close",native:"To close"},{text:"To give",native:"To give"},{text:"To take",native:"To take"},{text:"To find",native:"To find"},{text:"To think",native:"To think"},{text:"To know",native:"To know"},{text:"To love",native:"To love"},{text:"To help",native:"To help"},
    {text:"Happy",native:"Happy"},{text:"Sad",native:"Sad"},{text:"Angry",native:"Angry"},{text:"Afraid",native:"Afraid"},{text:"Surprised",native:"Surprised"},{text:"Tired",native:"Tired"},{text:"Hungry",native:"Hungry"},{text:"Thirsty",native:"Thirsty"},{text:"Brave",native:"Brave"},{text:"Love",native:"Love"},{text:"Hope",native:"Hope"},{text:"Dream",native:"Dream"},{text:"Fear",native:"Fear"},{text:"Smile",native:"Smile"},{text:"Excited",native:"Excited"},{text:"Bored",native:"Bored"},{text:"Nervous",native:"Nervous"},{text:"Proud",native:"Proud"},{text:"Confused",native:"Confused"},{text:"Grateful",native:"Grateful"},
    {text:"Store",native:"Store"},{text:"Market",native:"Market"},{text:"Price",native:"Price"},{text:"Expensive",native:"Expensive"},{text:"Cheap",native:"Cheap"},{text:"Discount",native:"Discount"},{text:"Cash",native:"Cash"},{text:"Credit card",native:"Credit card"},{text:"Receipt",native:"Receipt"},{text:"Size",native:"Size"},{text:"Quality",native:"Quality"},{text:"Brand",native:"Brand"},
    {text:"Internet",native:"Internet"},{text:"Email",native:"Email"},{text:"Website",native:"Website"},{text:"Password",native:"Password"},{text:"Camera",native:"Camera"},{text:"Video",native:"Video"},{text:"Music",native:"Music"},{text:"Download",native:"Download"},{text:"Search",native:"Search"},{text:"Click",native:"Click"},{text:"Screen",native:"Screen"},{text:"Message",native:"Message"},
    {text:"Sun",native:"Sun"},{text:"Moon",native:"Moon"},{text:"Star",native:"Star"},{text:"Sky",native:"Sky"},{text:"Cloud",native:"Cloud"},{text:"Rain",native:"Rain"},{text:"Snow",native:"Snow"},{text:"Wind",native:"Wind"},{text:"Hot",native:"Hot"},{text:"Cold",native:"Cold"},{text:"Tree",native:"Tree"},{text:"Flower",native:"Flower"},{text:"Forest",native:"Forest"},{text:"River",native:"River"},{text:"Sea",native:"Sea"},{text:"Fire",native:"Fire"},{text:"Earth",native:"Earth"},{text:"Air",native:"Air"},{text:"Animal",native:"Animal"},{text:"Dog",native:"Dog"},{text:"Cat",native:"Cat"},{text:"Bird",native:"Bird"},{text:"Horse",native:"Horse"},
    {text:"What is this?",native:"What is this?"},{text:"How much?",native:"How much?"},{text:"Where is?",native:"Where is?"},{text:"I don't understand",native:"I don't understand"},{text:"I don't know",native:"I don't know"},{text:"Do you speak English?",native:"Do you speak English?"},{text:"Please speak slowly",native:"Please speak slowly"},{text:"Can you help me?",native:"Can you help me?"},{text:"I need",native:"I need"},{text:"I like",native:"I like"},{text:"Good idea",native:"Good idea"},{text:"No problem",native:"No problem"},{text:"I'm lost",native:"I'm lost"},{text:"Call the police",native:"Call the police"},{text:"I need a doctor",native:"I need a doctor"},
    {text:"Left",native:"Left"},{text:"Right",native:"Right"},{text:"Straight",native:"Straight"},{text:"Near",native:"Near"},{text:"Far",native:"Far"},{text:"Here",native:"Here"},{text:"There",native:"There"},{text:"Inside",native:"Inside"},{text:"Outside",native:"Outside"},{text:"Up",native:"Up"},{text:"Down",native:"Down"},
    {text:"Cat",native:"Cat"},{text:"Dog",native:"Dog"},{text:"Bird",native:"Bird"},{text:"Fish animal",native:"Fish animal"},{text:"Horse",native:"Horse"},{text:"Cow",native:"Cow"},{text:"Pig",native:"Pig"},{text:"Elephant",native:"Elephant"},{text:"Lion",native:"Lion"},{text:"Monkey",native:"Monkey"},
  ],
};

export async function POST(request: Request) {
  const { language, courseId } = await request.json();
  const words = WORD_DATA[language];
  
  if (!words) return NextResponse.json({ error: "Unknown language" }, { status: 400 });
  if (!courseId) return NextResponse.json({ error: "Missing courseId" }, { status: 400 });

  console.log(`Seeding ${words.length} words for ${language}`);

  const supabase = await createClient();
  const batch = words.map((w, i) => ({
    course_id: courseId,
    text: w.text,
    native_text: w.native,
    order_index: i,
  }));

  const { error } = await supabase.from("words").insert(batch);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  await supabase.from("courses").update({ word_count: words.length }).eq("id", courseId);
  
  return NextResponse.json({ success: true, count: words.length });
}
